var ctiyNameConversion = {
  "臺北市": "Taipei_City",
  "臺北": "Taipei_City",
  "台北市": "Taipei_City",
  "台北": "Taipei_City",
  "taipei": "Taipei_City",
  "Taipei": "Taipei_City",
  "新北市": "New_Taipei_City",
  "新北": "New_Taipei_City",
  "New Taipei": "New_Taipei_City",
  "new taipei": "New_Taipei_City",
  "台北縣": "New_Taipei_City",
  "基隆市": "Keelung_City",
  "基隆": "Keelung_City",
  "keelung": "Keelung_City",
  "Keelung": "Keelung_City",
  "宜蘭縣": "Yilan_County",
  "宜蘭": "Yilan_County",
  "yilan": "Yilan_County",
  "Yilan": "Yilan_County",
  "桃園市": "Taoyuan_City",
  "桃園": "Taoyuan_City",
  "taoyuan": "Taoyuan_City",
  "Taoyuan": "Taoyuan_City",
  "新竹市": "Hsinchu_City",
  "新竹": "Hsinchu_City",
  "hsinchu": "Hsinchu_City",
  "Hsinchu": "Hsinchu_City",
  "新竹縣": "Hsinchu_County",
  "苗栗縣": "Miaoli_County",
  "苗栗": "Miaoli_County",
  "miaoli": "Miaoli_County",
  "Miaoli": "Miaoli_County",
  "彰化縣": "Changhua_County",
  "彰化": "Changhua_County",
  "changhua": "Changhua_County",
  "Changhua": "Changhua_County",
  "臺中市": "Taichung_City",
  "臺中": "Taichung_City",
  "taichung": "Taichung_City",
  "Taichung": "Taichung_City",
  "台中": "Taichung_City",
  "南投縣": "Nantou_County",
  "南投": "Nantou_County",
  "nantou": "Nantou_County",
  "Nantou": "Nantou_County",
  "雲林縣": "Yunlin_County",
  "雲林": "Yunlin_County",
  "Yunlin": "Yunlin_County",
  "yunlin": "Yunlin_County",
  "嘉義市": "Chiayi_City",
  "嘉義": "Chiayi_City",
  "Chiayi": "Chiayi_City",
  "chiayi": "Chiayi_City",
  "嘉義縣": "Chiayi_County",
  "臺南市": "Tainan_City",
  "臺南": "Tainan_City",
  "Tainan": "Tainan_City",
  "tainan": "Tainan_City",
  "高雄市": "Kaohsiung_City",
  "高雄": "Kaohsiung_City",
  "Kaohsiung": "Kaohsiung_City",
  "kaohsiung": "Kaohsiung_City",
  "屏東縣": "Pingtung_County",
  "屏東": "Pingtung_County",
  "Pingtung": "Pingtung_County",
  "pingtung": "Pingtung_County",
  "花蓮縣": "Hualien_County",
  "花蓮": "Hualien_County",
  "Hualien": "Hualien_County",
  "hualien": "Hualien_County",
  "臺東縣": "Taitung_County",
  "臺東": "Taitung_County",
  "Taitung": "Taitung_County",
  "taitung": "Taitung_County",
  "澎湖縣": "Penghu_County",
  "澎湖": "Penghu_County",
  "Penghu": "Penghu_County",
  "penghu": "Penghu_County",
  "金門縣": "Kinmen_County",
  "金門": "Kinmen_County",
  "Kinmen": "Kinmen_County",
  "kinmen": "Kinmen_County",
  "連江縣": "Lienchiang_County",
  "連江": "Lienchiang_County",
  "Lienchiang": "Lienchiang_County",
  "lienchiang": "Lienchiang_County",
  "馬祖縣": "Lienchiang_County",
  "馬祖": "Lienchiang_County",
  "Matsu": "Lienchiang_County",
  "matsu": "Lienchiang_County"
}

function regularCityName(city) {
  var cityName = ctiyNameConversion[city];
  return cityName;
}


// console.log(regularCityName('連'));

module.exports = regularCityName;
